version: '3.3'

services:
   db:
     image: mysql:5.7
     restart: always
     networks:
      - api
     environment:
       MYSQL_ROOT_PASSWORD: "fafa1"
       MYSQL_DATABASE: "climbing"

   spring:
     depends_on:
       - db
     build: zone/
     networks:
      - api
     ports:
      - "8080:8080"
     expose:
      - "8080"
     restart: always
     environment:
      DB_NAME: "climbing"
      DB_USER: "root"
      DB_PASSWORD: "fafa1"
      DB_URL: db

   #react2:
   #  depends_on:
   #    - spring
   #  build: react2/
   #  networks:
   #   - api
   #  ports:
   #   - "8081:8081"
   #  expose:
   #   - "8081"
   #  restart: always

   angular:
     depends_on:
      - spring
     build: angular/
     networks:
      - api
     ports:
     - "4200:4200"
     expose:
     - "4200"
     restart: always

networks:
  api: