version: '3.3'

services:
   db:
     image: mysql:5.7
     restart: always
     networks:
      - api
     ports:
      - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: "fafa1"
       MYSQL_DATABASE: "climbing"

   spring:
     depends_on:
       - db
     build: zone/
     networks:
      - api
     ports:
      - "8080:8080"
     expose:
      - "8080"
     restart: always
     environment:
      DB_NAME: "climbing"
      DB_USER: "root"
      DB_PASSWORD: "fafa1"
      DB_URL: db
      DB_PORT: "3306"
      
networks:
      api:
