package com.climbing.zone.enumeration;

public enum BonusType {
    JUMP, SLOPE, DYNAMIC, CRUX, CROOSHAND, FEET, HAND, ROOF, WALL, BI, TRI, MONO, PINCH, DIHEDRAL, LOW_ANGLE_SLAB,
    OVERHANG, SLAB, STEEP_WALL, BUMP, NO_FOOT, CORE_STRENCH, DANGEROUS, DYNO, FOOT_WORK, FRICTION, HEEL_HOOK, REACHY, SQUEEZE
}
