# docker compose up
version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'climbing'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'fafa1'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'fafa1'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - ./data:/var/lib/mysql
