FROM node:8.7.0-alpine

WORKDIR /app
# EXPOSE 3000
COPY . ./
COPY package.json and COPY package-lock.json
RUN npm install
# COPY . /app/directory/path #
# CMD ["npm", "start"]
RUN npm build


COPY --from=react-build /app/build /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]